spring.application.name=blogproject
spring.thymeleaf.cache=false

spring.data.mongodb.uri=mongodb://localhost:27017/galeria
spring.data.mongodb.database=galeria


sightengine.api.user=${SIGHTENGINE_API_USER:497934805}
sightengine.api.secret=${SIGHTENGINE_API_SECRET:4ZWMhrMjcBoExJavMXGSkt6KAxASdwKb}

app.uploads.dir=${APP_UPLOADS_DIR:uploads}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8081

# Umbrales de moderacion (heredados de main, configurables por propiedad)
# Nudity
moderation.threshold.nudity.sexual_activity=0.05
moderation.threshold.nudity.sexual_display=0.10
moderation.threshold.nudity.erotica=0.20
moderation.threshold.nudity.very_suggestive=0.90

# Violence
moderation.threshold.violence.global=0.5
moderation.threshold.violence.physical=0.5
moderation.threshold.violence.firearm=0.4

# Drugs
moderation.threshold.drugs.recreational=0.10
moderation.threshold.drugs.medical=0.85
